version: 2.1

# Define templates to be reused across multiple jobs
run_script: &run_script
  steps:
    - checkout
    - run:
        name: Install Dependencies
        command: |
          sudo apt update 
          sudo apt install zlib1g-dev libsqlite3-dev libmemcached-dev memcached
          sudo docker-php-ext-install zip
          sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath      
          sudo docker-php-ext-install pdo_mysql
          #sudo docker-php-ext-install pcntl
          
          # sudo phpenv config-rm xdebug.ini || true      
          
          #Install and enable memcached extension
          printf "\n" | sudo pecl install -f memcached-3.1.3          
          sudo docker-php-ext-enable memcached
          
          # Install and enable redis extension
          printf "\n" | sudo pecl install -f redis-4.3.0         
          sudo docker-php-ext-enable redis
      
          # Install and enable iconv and gd exensions
          sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
          sudo docker-php-ext-install -j$(nproc) iconv
          sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          sudo docker-php-ext-install -j$(nproc) gd
          
          sudo composer self-update
    - restore_cache:
        key: composer-${PHP_VERSION}
    - run:
        name: Composer Update
        command: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
    - save_cache:
        key: composer-${PHP_VERSION}
        paths:
          - ~/.composer/cache
    - run: vendor/bin/phpunit -d memory_limit=512M          

jobs:
  php_7_3:
    environment:
      PHP_VERSION: 7.3
      SETUP: stable
    docker:
      - image: circleci/php:7.3-cli-stretch
        environment:
          SETUP: stable
      - image: circleci/mysql:5.7
#         command: [--default-authentication-plugin=mysql_native_password]
        environment:          
#           MYSQL_ROOT_PASSWORD: ""
#           MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: forge
      - image: memcached
      - image: circleci/redis:4    
    <<: *run_script

workflows:
  version: 2
  build:
    jobs:
      - php_7_3
