version: 2.1

jobs:
  build_machine:
    machine:
      image: ubuntu-1604:201903-01
#     environment:      
#       deps: low
#       TRAVIS_PHP_VERSION: 7.3
#       PHP_VERSION: 7.3    
    environment:
      PHP_VERSION: 7.3
    steps:
      - checkout
      - run:
          name: Install PHP
          command: |          
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157        
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install -y php${PHP_VERSION} 
            sudo apt-get install -y php${PHP_VERSION}-dev php${PHP_VERSION}-cli php${PHP_VERSION}-common php${PHP_VERSION}-bcmath php${PHP_VERSION}-intl php${PHP_VERSION}-json php${PHP_VERSION}-opcache php${PHP_VERSION}-mysql php${PHP_VERSION}-mbstring php${PHP_VERSION}-zip php${PHP_VERSION}-fpm            
            if [[ PHP_VERSION = 7.1 ]]; then
              sudo apt-get install -y php${PHP_VERSION}-mcrypt
            fi        

            # Install pear
            sudo apt-get install -y php${PHP_VERSION}-xml php-pear

            # Install memcached
            sudo apt-get install -y libz-dev libmemcached-dev

            # Install composer
            sudo curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer 
            
            sudo phpenmod pdo_mysql
            sudo service apache2 restart
            
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libmemcached-dev libzip-dev
      #- run: sudo docker-php-ext-install zip
      #- run: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath      
      #- run: sudo docker-php-ext-install pdo_mysql
      - run: printf "\n" | sudo pecl install -f memcached-3.1.3
      - run: printf "\n" | sudo pecl install -f redis-4.3.0
#       - run: printf "\n" | sudo pecl install -f zip
#       - run: printf "\n" | sudo pecl install -f bcmath
#       - run: echo "extension = memcached.so" >> /opt/circleci/php/$(phpenv global)/etc/php.ini
#       - run: echo -e "[Date]\ndate.timezone = UTC" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run: echo "extension = memcached.so" | sudo tee -a /etc/php/7.3/cli/php.ini > /dev/null
#       - run: echo "extension = zip.so" | sudo tee -a /etc/php/7.3/cli/php.ini > /dev/null
      #/etc/php/$PHP/cli/conf.d/travis.ini
      - run: sudo composer self-update
#       - restore_cache:
#           key: composer
      - run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
      - run: vendor/bin/phpunit -d memory_limit=512M

  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
        environment:
          SETUP: stable
#           REDIS_HOST: redis
#           REDIS_PORT: 6379
      - image: circleci/mysql:5.7
#         command: [--default-authentication-plugin=mysql_native_password]
        environment:          
#           MYSQL_ROOT_PASSWORD: ""
#           MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: forge
#       - image: memcached:1.5-alpine
      - image: circleci/redis:4
    environment:
      SETUP: stable
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libmemcached-dev memcached
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath      
      - run: sudo docker-php-ext-install pdo_mysql
      # - run: sudo phpenv config-rm xdebug.ini || true      
      - run: printf "\n" | sudo pecl install -f memcached-3.1.3
      - run: printf "\n" | sudo pecl install -f redis-4.3.0
#       - run: echo "extension = memcached.so" >> /opt/circleci/php/$(phpenv global)/etc/php.ini
#       - run: echo -e "[Date]\ndate.timezone = UTC" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run: echo "extension = memcached.so" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run: sudo composer self-update
      - restore_cache:
          key: composer
      - run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      # - run: touch storage/testing.sqlite 
      # - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: sudo service memcached status || true
      - run: sudo service memcached start
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: vendor/bin/phpunit -d memory_limit=512M
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples   

workflows:
  version: 2
  build:
    jobs:
#       - build_machine
      - build
