version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
      - image: circleci/mysql:5.7-ram
    environment:
      - SETUP: stable
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath      
      # - run: sudo phpenv config-rm xdebug.ini || true
      - run: sudo composer self-update
      - restore_cache:
          key: composer
      - run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      # - run: touch storage/testing.sqlite 
      # - run: php artisan migrate --env=testing --database=sqlite_testing --force
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run
      - run: vendor/bin/phpunit -d memory_limit=512M
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples   
