version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
      - image: circleci/mysql:5.7-ram
        environment:          
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: forge
      - image: memcached:1.5-alpine
    environment:
      - SETUP: stable
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libmemcached-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath      
      - run: sudo docker-php-ext-install pdo_mysql
      # - run: sudo phpenv config-rm xdebug.ini || true      
      - run: printf "\n" | sudo pecl install -f memcached-2.1.0
#       - run: echo "extension = memcached.so" >> /opt/circleci/php/$(phpenv global)/etc/php.ini
#       - run: echo -e "[Date]\ndate.timezone = UTC" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run: echo "extension = memcached.so" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run: sudo composer self-update
      - restore_cache:
          key: composer
      - run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      # - run: touch storage/testing.sqlite 
      # - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: vendor/bin/phpunit -d memory_limit=512M
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples   
